name: Azure Functions .NET Core CI/CD
env:
    OUTPUT_PATH: ${{ github.workspace }}/.output
    DOTNET_VERSION: "3.1.300"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup .NET Core ${{ env.DOTNET_VERSION }} SDK
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Build App
      run: dotnet publish src/SpreadsheetHandlers/SpreadsheetHandlers.csproj -c Release -o ${{ env.OUTPUT_PATH }}
    - name: Package functions
      uses: actions/upload-artifact@v2
      with:
        name: functions
        path: ${{ env.OUTPUT_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    env:
        FUNC_APP_NAME: SpreadsheetHandler20200712183049  
    steps:
    - name: Download function
      uses: actions/download-artifact@v2
      with:
          name: functions
          path: ${{ env.OUTPUT_PATH }}
    - name: "Login via Azure CLI"
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: "Run Azure Functions Action"
      uses: Azure/functions-action@v1.1.4
      with:
        app-name: ${{ env.FUNC_APP_NAME }}
        package: ${{ env.OUTPUT_PATH }}
    
